# Site settings
title: Chirag Aggarwal
email: chi6rag@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm a software developer and an Aspiring Entrepreneur
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chi6rag.github.io" # the base hostname & protocol for your site
twitter_username: chi6rag
github_username:  chi6rag

# Build settings
markdown: kramdown
